name: ViroCatch-DNA_env
channels:
  - bioconda/label/cf201901
  - bioconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - awk=20250116=h6e16a3a_0
  - blast=2.16.0=h53185c9_5
  - brotli-python=1.1.0=py38h940360d_1
  - bzip2=1.0.8=hfdf4475_7
  - c-ares=1.34.5=hf13058a_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - canu=1.4=1
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38hc8bcfa4_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - curl=8.13.0=h5dec5d8_0
  - entrez-direct=22.4=h193322a_0
  - fastp=0.24.1=h9ea9c2a_0
  - fastplong=0.2.2=h9ea9c2a_0
  - flye=2.9.5=py38hb55279e_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h37eeddb_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=h694c41f_1
  - gnuplot=5.0.3=4
  - gzip=1.14=h6e16a3a_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=h120a0e1_0
  - idna=3.10=pyhd8ed1ab_0
  - isa-l=2.31.1=h6e16a3a_1
  - java-jdk=8.0.112=1
  - kraken2=2.14=pl5321he136a0b_0
  - krakentools=1.2=pyh7e72e81_1
  - krb5=1.21.3=h37d8d59_0
  - lerc=4.0.0=hcca01a6_1
  - libasprintf=0.24.1=h27064b9_0
  - libblas=3.9.0=20_osx64_openblas
  - libcblas=3.9.0=20_osx64_openblas
  - libcurl=8.13.0=h5dec5d8_0
  - libcxx=20.1.4=hf95d169_1
  - libdeflate=1.22=h00291cd_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libexpat=2.7.0=h240833e_0
  - libffi=3.4.6=h281671d_1
  - libfreetype=2.13.3=h694c41f_1
  - libfreetype6=2.13.3=h40dfd5c_1
  - libgd=2.3.3=h8555400_11
  - libgettextpo=0.24.1=h27064b9_0
  - libgfortran=14.2.0=hef36b68_105
  - libgfortran5=14.2.0=h58528f3_105
  - libiconv=1.18=h4b5e92a_1
  - libidn2=2.3.8=he8ff88c_0
  - libintl=0.24.1=h27064b9_0
  - libjpeg-turbo=3.1.0=h6e16a3a_0
  - liblapack=3.9.0=20_osx64_openblas
  - liblzma=5.8.1=hd471939_1
  - liblzma-devel=5.8.1=hd471939_1
  - libnghttp2=1.64.0=hc7306c3_0
  - libopenblas=0.3.25=openmp_hfef2a42_0
  - libpng=1.6.47=h3c4a55f_0
  - libsqlite=3.49.2=hdb6dae5_0
  - libssh2=1.11.1=hed3591d_0
  - libtiff=4.7.0=hf4bdac2_2
  - libunistring=0.9.10=h0d85af4_0
  - libwebp-base=1.5.0=h6cf52b4_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=20.1.4=ha54dae1_0
  - lz4-c=1.10.0=h240833e_1
  - ncbi-vdb=3.2.1=h5fa12a8_0
  - ncurses=6.5=h0622a9a_3
  - numpy=1.24.4=py38h9a4a08f_0
  - openjdk=8.0.112=zulu8.19.0.1_3
  - openssl=3.5.0=hc426f3f_1
  - packaging=25.0=pyh29332c3_1
  - perl=5.32.1=7_h10d778d_perl5
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-carp=1.38=pl5321hdfd78af_4
  - perl-common-sense=3.75=pl5321hdfd78af_0
  - perl-compress-raw-bzip2=2.201=pl5321h9722bc1_0
  - perl-compress-raw-zlib=2.105=pl5321h9722bc1_0
  - perl-encode=3.19=pl5321ha5712d3_1
  - perl-exporter=5.72=pl5321hdfd78af_2
  - perl-exporter-tiny=1.002002=pl5321hdfd78af_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-filesys-df=0.92=pl5321h18d8cf3_9
  - perl-io-compress=2.201=pl5321h5eaf441_5
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321h5fa12a8_4
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h18d8cf3_5
  - perl-parent=0.236=pl5321hdfd78af_2
  - perl-pathtools=3.75=pl5321ha5712d3_3
  - perl-scalar-list-utils=1.62=pl5321ha5712d3_0
  - perl-threaded=5.32.1=hdfd78af_1
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pip=24.3.1=pyh8b19718_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - popt=1.16=1
  - pycparser=2.22=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.20=h4f978b9_2_cpython
  - python_abi=3.8=7_cp38
  - readline=8.2=h7cca4af_2
  - requests=2.32.3=pyhd8ed1ab_0
  - rpsbproc=0.5.0=heca6186_3
  - rsync=3.4.1=hf2bfba0_2
  - scipy=1.10.1=py38h9cf86d3_3
  - spades=4.2.0=h62d8197_0
  - tar=1.34=hcb2f6ea_1
  - tk=8.6.13=h1abcd95_1
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wget=1.21.4=hca547e6_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xxhash=0.8.3=h13e91ac_0
  - xz=5.8.1=h357f2ed_1
  - xz-gpl-tools=5.8.1=h357f2ed_1
  - xz-tools=5.8.1=hd471939_1
  - zlib=1.3.1=hd23fc13_2
  - zstandard=0.19.0=py38hef030d1_0
  - zstd=1.5.7=h8210216_2
  - pip:
      - biopython==1.79
      - contourpy==1.1.1
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fonttools==4.57.0
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - matplotlib==3.7.5
      - openpyxl==3.1.2
      - pandas==1.5.3
      - pillow==10.4.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - recentrifuge==1.16.1
      - setuptools==75.3.2
      - six==1.17.0
      - zipp==3.20.2
prefix: /Users/felixmoran/miniconda3/envs/ViroCatch-DNA_env
